languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
hasCJKLanguage = true
weight = 1

title = "Everybody Wants Some"
copyright = "&copy; 2024 Kerria"

[params]
dateFormat = "2006-01-02 15:04 -07:00 Monday"
mainSections = ["posts"]
description = "unacro 的个人博客"

[params.author]
name = "Kerria"
image = "img/author.jpg"
headline = "Everybody wants some"
bio = "孤岛高山何其多 而你从来不抬头"
links = [
  { email = "mailto:po@ews.ink" },
  { github = "https://github.com/unacro" },
]

[permalinks]
[permalinks.page]
posts = '/posts/:year/:slugorfilename/'
tutorials = '/training/:slugorfilename/'
[permalinks.section]
posts = '/posts/'
tutorials = '/training/'
# [permalinks.term]
# tags = '/:slugorfilename/'
