languageCode = "zh-CN"
languageName = "简体中文"
languageDirection = "ltr"
weight = 2

title = "Everybody Wants Some"
copyright = "&copy; 2024 Kerria"

[params]
dateFormat = "2006-01-02"

mainSections = ["posts"]
description = "一款基于Tailwindcss的强大且轻量的Hugo主题"

[params.author]
name = "Kerria"
image = "img/author.jpg"
headline = "无所谓的明天却后悔的昨夜<br>挣扎在所难免放纵却无条件"
bio = "孤岛高山何其多 而你从来不抬头"
links = [
  { github = "https://github.com/unacro" },
  { discord = "https://nav.osrp.run/s/discord" },
  { afadian = "https://afadian.com/unacro" },
]
