[[subnavigation]]
name = "测试"
pre = "wand-magic-sparkles"
pageRef = "test"
weight = 1

[[subnavigation]]
name = "我有一个主意"
pre = "lightbulb"
pageRef = "ideas"
weight = 10

[[subnavigation]]
name = "有空一起挨打"
pre = "skull-crossbones"
pageRef = "interests"
weight = 20

[[subnavigation]]
name = "这位更是重在参与"
pre = "ghost"
pageRef = "projects"
weight = 30
