[[imports]]
disable = false
path = "github.com/unacro/games-static-database"

[[imports]]
disable = true
path = "github.com/nunocoracao/blowfish/v2"

[[imports]]
disable = false
path = "github.com/unacro/hugo-theme-blowfish-mod"

[[imports]]
disable = false
path = "github.com/unacro/hugo-shortcodes"
