theme = "blowfish"
baseURL = "https://ews.ink/"

buildDrafts = false
buildExpired = false
buildFuture = false


[[module.imports]]
# 禁用远程的 Hugo module(Go module) 而使用 .Site.Params.theme 设置的本地主题(Git submodule)
disable = true
path = "github.com/nunocoracao/blowfish/v2"

[[module.imports]]
disable = false
path = "github.com/unacro/hugo-theme-blowfish-mod"

[[module.imports]]
disable = false
path = "github.com/unacro/games-static-database"

[[module.imports]]
disable = false
path = "github.com/unacro/hugo-shortcodes"
